// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQOw_VcVce6hc8MpOgySKyBm_MehODrI',
    appId: '1:976019883217:web:4d3220729750e866fcb1f0',
    messagingSenderId: '976019883217',
    projectId: 'talabat-clone-21217',
    authDomain: 'talabat-clone-21217.firebaseapp.com',
    storageBucket: 'talabat-clone-21217.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAigKKKE9xFgKV3kdjB12jRxxklZAaxmTQ',
    appId: '1:976019883217:android:cd772d7d0ed816f1fcb1f0',
    messagingSenderId: '976019883217',
    projectId: 'talabat-clone-21217',
    storageBucket: 'talabat-clone-21217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjeXyQvFfwP83Nzri8UXnEpjSCKjQvqKI',
    appId: '1:976019883217:ios:1c3b51a0e639deadfcb1f0',
    messagingSenderId: '976019883217',
    projectId: 'talabat-clone-21217',
    storageBucket: 'talabat-clone-21217.firebasestorage.app',
    iosBundleId: 'com.example.talabatClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjeXyQvFfwP83Nzri8UXnEpjSCKjQvqKI',
    appId: '1:976019883217:ios:1c3b51a0e639deadfcb1f0',
    messagingSenderId: '976019883217',
    projectId: 'talabat-clone-21217',
    storageBucket: 'talabat-clone-21217.firebasestorage.app',
    iosBundleId: 'com.example.talabatClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQOw_VcVce6hc8MpOgySKyBm_MehODrI',
    appId: '1:976019883217:web:f2e29e548cb8e3effcb1f0',
    messagingSenderId: '976019883217',
    projectId: 'talabat-clone-21217',
    authDomain: 'talabat-clone-21217.firebaseapp.com',
    storageBucket: 'talabat-clone-21217.firebasestorage.app',
  );
}
